from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter, A4
from reportlab.lib.units import inch
from reportlab.lib import colors
from datetime import datetime
import os

def generate_system_report(data):
    """Generate a detailed PDF system report"""
    filename = f"system_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
    
    c = canvas.Canvas(filename, pagesize=A4)
    width, height = A4
    
    # Title
    c.setFont("Helvetica-Bold", 20)
    c.drawString(1*inch, height - 1*inch, "SMART SYSTEM DOCTOR")
    c.setFont("Helvetica", 12)
    c.drawString(1*inch, height - 1.4*inch, "System Health & Security Report")
    
    # Date
    c.setFont("Helvetica", 10)
    c.drawString(1*inch, height - 1.7*inch, f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    
    # Divider line
    c.line(1*inch, height - 1.9*inch, 7.5*inch, height - 1.9*inch)
    
    # System Metrics
    y_position = height - 2.3*inch
    c.setFont("Helvetica-Bold", 14)
    c.drawString(1*inch, y_position, "SYSTEM METRICS")
    c.setFont("Helvetica", 11)
    
    metrics = [
        (f"CPU Usage", f"{data['cpu']:.1f}%"),
        (f"RAM Usage", f"{data['ram']:.1f}%"),
        (f"Disk Usage", f"{data['disk']:.1f}%"),
        (f"Active Processes", str(data.get('process_count', 0))),
        (f"Health Score", f"{data['health_score']}/100"),
        (f"Security Score", f"{data['security_score']}/100"),
    ]
    
    y_position -= 0.3*inch
    for label, value in metrics:
        c.drawString(1.5*inch, y_position, f"{label}: {value}")
        y_position -= 0.25*inch
    
    # Health Status
    y_position -= 0.2*inch
    c.setFont("Helvetica-Bold", 14)
    c.drawString(1*inch, y_position, "HEALTH STATUS")
    c.setFont("Helvetica", 11)
    y_position -= 0.3*inch
    c.drawString(1.5*inch, y_position, data.get('health_state', 'Unknown'))
    
    # Security Status
    y_position -= 0.3*inch
    c.setFont("Helvetica-Bold", 14)
    c.drawString(1*inch, y_position, "SECURITY STATUS")
    c.setFont("Helvetica", 11)
    y_position -= 0.3*inch
    c.drawString(1.5*inch, y_position, data.get('security_state', 'Unknown'))
    
    # Threats
    if data.get('threats'):
        y_position -= 0.3*inch
        c.setFont("Helvetica-Bold", 12)
        c.drawString(1*inch, y_position, "⚠ Detected Threats:")
        c.setFont("Helvetica", 9)
        y_position -= 0.25*inch
        for threat in data['threats'][:5]:  # Show top 5 threats
            c.drawString(1.5*inch, y_position, f"• {threat.get('name', 'Unknown')} - {threat.get('severity', 'UNKNOWN')}")
            y_position -= 0.2*inch
    
    # Footer
    c.setFont("Helvetica", 8)
    c.drawString(1*inch, 0.5*inch, "Generated by Smart System Doctor v4.0")
    
    c.save()
    return filename